# Generated by Django 5.0.6 on 2024-06-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='apellidoChofer',
            field=models.CharField(max_length=40, verbose_name='Apellido Chofer'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='capacidad',
            field=models.IntegerField(verbose_name='Capacidad'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patenteVehiculo',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Patente Vehiculo'),
        ),
    ]
