# Generated by Django 5.0.6 on 2024-06-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_chofer_apellidochofer_alter_vehiculo_capacidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='telefono',
            field=models.CharField(default=0, max_length=15, verbose_name='Teléfono'),
            preserve_default=False,
        ),
    ]
