# Generated by Django 5.0.6 on 2024-07-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chofer_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='reservado',
            field=models.BooleanField(default=False, verbose_name='Reservado'),
        ),
    ]
